[package]
name = "ruffbox-sampler"
version = "0.1.0"
authors = ["nik <nik@parkellipsen.de>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
num = "0.2.0"
lazy_static = "1.2.0"
wee_alloc = { version = "0.4.2", optional = true }


